version: '3.8'

networks:
  email_net:
    name: email_net

services:

  email-api-service:
    build:
      context: ./
      dockerfile: ./docker/Dev.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    image: email-api-service_dev
    environment:
      APP_URL: "https://email-api-service.localhost"
      APP_DEBUG: true
      APP_ENV: local
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/app
      - ~/.config/composer:/home/myswooop/.composer
      - ~/.cache/composer:/home/myswooop/.composer/cache
    networks:
      - email_net
    labels:
      traefik.enable: true
      traefik.http.routers.email-api-service_https.rule: Host(`email-api-service.localhost`)
      traefik.http.routers.email-api-service_https.entrypoints: web,websecure
      traefik.http.routers.email-api-service_https.tls: true

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - email_net

  redis:
    image: redis:6-alpine
    networks:
     - email_net

